# Generated by Django 5.0.6 on 2026-05-13 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('server', 'Сервер'), ('pc', 'Компьютер'), ('notebook', 'Ноутбук'), ('monitor', 'Монитор'), ('printer', 'Принтер'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('in_use', 'В использовании'), ('in_storage', 'На складе'), ('in_repair', 'В ремонте'), ('written_off', 'Списано')], default='in_storage', max_length=20, verbose_name='Статус')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Местонахождение')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.employee', verbose_name='Назначено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('created', 'Создано'), ('updated', 'Обновлено'), ('assigned', 'Назначено'), ('unassigned', 'Снято назначение'), ('synced_1c', 'Синхронизировано из 1С')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-changed_at'],
            },
        ),
    ]
